name: 部署到 GitHub Pages

on:
  push:
    branches:
      - development
    # 如果你想要进一步定义触发、路径以及其他内容，请检阅 Github Actions 文档
    # https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: 构建 Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # 缓存 npm

      - name: 安装依赖
        run: npm ci # 使用 npm ci 确保安装的是 package-lock.json 中锁定的版本
      - name: 构建网站
        run: npm run build

      - name: 上传构建制品
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    name: 部署到 GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pre check
        run: ls -l

      - name: 下载构建制品
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: 解压构建制品
        run: |
          mkdir build
          unzip build.zip -d build

      - name: Check
        run: ls -l

      - name: 查看构建目录
        run: ls -la build

      - name: 部署到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main
          build_dir: build
          repo: carrgan/carrgan.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
