name: 部署到 GitHub Pages

on:
  push:
    branches:
      - development
    # 如果你想要进一步定义触发、路径以及其他内容，请检阅 Github Actions 文档
    # https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: CI Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: npm ci
        run: npm ci
      - name: npm build
        run: npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    name: Deploy GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main
          build_dir: build
          repo: carrgan/carrgan.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
